version: '2'
services:
        microservice:
                build: .
                image: go-app:1.0.1
                environment:
                        - PORT=8080
                ports: 
                        - "8080:8080"          
