---
# Source: helm-charts/templates/service.yaml
apiVersion: v1
kind: Service
metadata: 
  name: "go-app-secure"
  labels:
    helm.sh/chart: helm-charts-0.1.0
    app.kubernetes.io/name: helm-charts
    app.kubernetes.io/instance: go-app-secure
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    tier: service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: helm-charts
    app.kubernetes.io/instance: go-app-secure
---
# Source: helm-charts/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-secure
  labels:
    helm.sh/chart: helm-charts-0.1.0
    app.kubernetes.io/name: helm-charts
    app.kubernetes.io/instance: go-app-secure
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    
spec: 
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-charts
      app.kubernetes.io/instance: go-app-secure
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helm-charts
        app.kubernetes.io/instance: go-app-secure
        tier: service
    spec: 
      containers:
      - name: .Values.container.name }}
        image: "nginx"
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
# Source: helm-charts/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "go-app-secure-helm-charts-test-connection"
  labels:
    helm.sh/chart: helm-charts-0.1.0
    app.kubernetes.io/name: helm-charts
    app.kubernetes.io/instance: go-app-secure
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['go-app-secure-helm-charts:8080']
  restartPolicy: Never
