apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name | quote }}
  labels:
    {{- include "helm-charts.labels" . | nindent 4 }}
    tier: service
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    {{- include "helm-charts.selectorLabels" . | nindent 4 }}  